### ISSUE TITLE
Rendering when using vision environments [Question] 

### ISSUE THREAD

**Issue by team-daniel** [PKU-Alignment/safety-gymnasium#79]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

I am using the code below to play around with vision environments, I copied it from the documentation. When I run this I get the below error.
I want to have this env where the vision camera can be used as the state input. Thank you for your help

```python
import safety_gymnasium
import matplotlib.pyplot as plt

env = safety_gymnasium.make('SafetyCarGoal1Vision-v0', render_mode='human')

obs, info = env.reset()
terminated, truncated = False, False
ep_ret, ep_cost = 0, 0
for _ in range(1000):
    assert env.observation_space.contains(obs)
    act = env.action_space.sample()
    assert env.action_space.contains(act)
    # modified for Safe RL, added cost
    obs, reward, cost, terminated, truncated, info = env.step(act)
    ep_ret += reward
    ep_cost += cost
    if terminated or truncated:
        observation, info = env.reset()

    env.close()
``` 

```
  File ~/Documents/safety-gymnasium/safety_gymnasium/utils/passive_env_checker.py:25 in env_step_passive_checker
    result = env.step(action)

  File ~/Documents/safety-gymnasium/safety_gymnasium/builder.py:248 in step
    self.render()

  File ~/Documents/safety-gymnasium/safety_gymnasium/builder.py:314 in render
    assert (

AssertionError: When you use vision envs, you should not call this function explicitly.
```

**Comment by muchvo** [comment]
Thank you for your feedback! The cause of this error is due to a logic issue with rendering, where we have disabled the usage of 'human' as a `render_mode` while running in the Vision environment. The environment demonstrated in the documentation is `SafetyPointCircle0-v0`, and the absence of the 'Vision' suffix indicates that this is a vector information observation environment.

If you wish to save the rendered images in the Vision environment, you can refer to this example file for more information: `/examples/vision_env.py`.

And for the script your provided, just do modification like this:
```python
env = safety_gymnasium.make('SafetyCarGoal1Vision-v0')
```

I hope my response assists in resolving your issue. If you have any further questions, feel free to provide more information.

**Comment by team-daniel** [comment]
Thank you! I have it working now thanks to your help, your response was perfect and quick!
